COMMON_STATE_ALTERNATES = {
    # Australia
    'Australian Capital Territory': 'ACT',
    'ACT': 'ACT',
    'New South Wales': 'NSW',
    'NSW': 'NSW',
    'Victoria': 'VIC',
    'VIC': 'VIC',
    'Queensland': 'QLD',
    'QLD': 'QLD',
    'South Australia': 'SA',
    'SA': 'SA',
    'Western Australia': 'WA',
    'WA': 'WA',
    'Tasmania': 'TAS',
    'TAS': 'TAS',
    'Northern Territory': 'NT',
    'NT': 'NT',

    # Brazil
    'Acre': 'AC',
    'AC': 'AC',
    'Alagoas': 'AL',
    'AL': 'AL',
    'Amapá': 'AP',
    'AP': 'AP',
    'Amazonas': 'AM',
    'AM': 'AM',
    'Bahia': 'BA',
    'BA': 'BA',
    'Ceará': 'CE',
    'CE': 'CE',
    'Distrito Federal': 'DF',
    'DF': 'DF',
    'Espírito Santo': 'ES',
    'ES': 'ES',
    'Goiás': 'GO',
    'GO': 'GO',
    'Maranhão': 'MA',
    'MA': 'MA',
    'Mato Grosso': 'MT',
    'MT': 'MT',
    'Mato Grosso do Sul': 'MS',
    'MS': 'MS',
    'Minas Gerais': 'MG',
    'MG': 'MG',
    'Pará': 'PA',
    'PA': 'PA',
    'Paraíba': 'PB',
    'PB': 'PB',
    'Paraná': 'PR',
    'PR': 'PR',
    'Pernambuco': 'PE',
    'PE': 'PE',
    'Piauí': 'PI',
    'PI': 'PI',
    'Rio de Janeiro': 'RJ',
    'RJ': 'RJ',
    'Rio Grande do Norte': 'RN',
    'RN': 'RN',
    'Rio Grande do Sul': 'RS',
    'RS': 'RS',
    'Rondônia': 'RO',
    'RO': 'RO',
    'Roraima': 'RR',
    'RR': 'RR',
    'Santa Catarina': 'SC',
    'SC': 'SC',
    'São Paulo': 'SP',
    'SP': 'SP',
    'Sergipe': 'SE',
    'SE': 'SE',
    'Tocantins': 'TO',
    'TO': 'TO',

    # Canada
    'Alberta': 'AB',
    'AB': 'AB',
    'British Columbia': 'BC',
    'BC': 'BC',
    'Manitoba': 'MB',
    'MB': 'MB',
    'New Brunswick': 'NB',
    'NB': 'NB',
    'Newfoundland and Labrador': 'NL',
    'NL': 'NL',
    'Northwest Territories': 'NT',
    'NT': 'NT',
    'Nova Scotia': 'NS',
    'NS': 'NS',
    'Nunavut': 'NU',
    'NU': 'NU',
    'Ontario': 'ON',
    'ON': 'ON',
    'Prince Edward Island': 'PE',
    'PE': 'PE',
    'Quebec': 'QC',
    'QC': 'QC',
    'Saskatchewan': 'SK',
    'SK': 'SK',
    'Yukon': 'YT',
    'YT': 'YT',

    # China
    'Beijing': 'BJ',
    'BJ': 'BJ',
    'Tianjin': 'TJ',
    'TJ': 'TJ',
    'Hebei': 'HE',
    'HE': 'HE',
    'Shanxi': 'SX',
    'SX': 'SX',
    'Inner Mongolia': 'NM',
    'NM': 'NM',
    'Liaoning': 'LN',
    'LN': 'LN',
    'Jilin': 'JL',
    'JL': 'JL',
    'Heilongjiang': 'HL',
    'HL': 'HL',
    'Shanghai': 'SH',
    'SH': 'SH',
    'Jiangsu': 'JS',
    'JS': 'JS',
    'Zhejiang': 'ZJ',
    'ZJ': 'ZJ',
    'Anhui': 'AH',
    'AH': 'AH',
    'Fujian': 'FJ',
    'FJ': 'FJ',
    'Jiangxi': 'JX',
    'JX': 'JX',
    'Shandong': 'SD',
    'SD': 'SD',
    'Henan': 'HA',
    'HA': 'HA',
    'Hubei': 'HB',
    'HB': 'HB',
    'Hunan': 'HN',
    'HN': 'HN',
    'Guangdong': 'GD',
    'GD': 'GD',
    'Guangxi': 'GX',
    'GX': 'GX',
    'Hainan': 'HI',
    'HI': 'HI',
    'Chongqing': 'CQ',
    'CQ': 'CQ',
    'Sichuan': 'SC',
    'SC': 'SC',
    'Guizhou': 'GZ',
    'GZ': 'GZ',
    'Yunnan': 'YN',
    'YN': 'YN',
    'Tibet': 'XZ',
    'XZ': 'XZ',
    'Shaanxi': 'SN',
    'SN': 'SN',
    'Gansu': 'GS',
    'GS': 'GS',
    'Qinghai': 'QH',
    'QH': 'QH',
    'Ningxia': 'NX',
    'NX': 'NX',
    'Xinjiang': 'XJ',
    'XJ': 'XJ',
    'Taiwan': 'TW',
    'TW': 'TW',
    'Hong Kong': 'HK',
    'HK': 'HK',
    'Macao': 'MO',
    'MO': 'MO',

    # Ireland
    'Carlow': 'CW',
    'CW': 'CW',
    'Cavan': 'CN',
    'CN': 'CN',
    'Clare': 'CE',
    'CE': 'CE',
    'Cork': 'CO',
    'CO': 'CO',
    'Donegal': 'DL',
    'DL': 'DL',
    'Dublin': 'D',
    'D': 'D',
    'Galway': 'G',
    'G': 'G',
    'Kerry': 'KY',
    'KY': 'KY',
    'Kildare': 'KE',
    'KE': 'KE',
    'Kilkenny': 'KK',
    'KK': 'KK',
    'Laois': 'LS',
    'LS': 'LS',
    'Leitrim': 'LM',
    'LM': 'LM',
    'Limerick': 'LK',
    'LK': 'LK',
    'Longford': 'LD',
    'LD': 'LD',
    'Louth': 'LH',
    'LH': 'LH',
    'Mayo': 'MO',
    'MO': 'MO',
    'Meath': 'MH',
    'MH': 'MH',
    'Monaghan': 'MN',
    'MN': 'MN',
    'Offaly': 'OY',
    'OY': 'OY',
    'Roscommon': 'RN',
    'RN': 'RN',
    'Sligo': 'SO',
    'SO': 'SO',
    'Tipperary': 'TA',
    'TA': 'TA',
    'Waterford': 'WD',
    'WD': 'WD',
    'Westmeath': 'WH',
    'WH': 'WH',
    'Wexford': 'WX',
    'WX': 'WX',
    'Wicklow': 'WW',
    'WW': 'WW',

    # India
    'Andaman and Nicobar Islands': 'AN',
    'AN': 'AN',
    'Andhra Pradesh': 'AP',
    'AP': 'AP',
    'Arunachal Pradesh': 'AR',
    'AR': 'AR',
    'Assam': 'AS',
    'AS': 'AS',
    'Bihar': 'BR',
    'BR': 'BR',
    'Chandigarh': 'CH',
    'CH': 'CH',
    'Chhattisgarh': 'CT',
    'CT': 'CT',
    'Dadra and Nagar Haveli and Daman and Diu': 'DD',
    'DD': 'DD',
    'Delhi': 'DL',
    'DL': 'DL',
    'Goa': 'GA',
    'GA': 'GA',
    'Gujarat': 'GJ',
    'GJ': 'GJ',
    'Haryana': 'HR',
    'HR': 'HR',
    'Himachal Pradesh': 'HP',
    'HP': 'HP',
    'Jammu and Kashmir': 'JK',
    'JK': 'JK',
    'Jharkhand': 'JH',
    'JH': 'JH',
    'Karnataka': 'KA',
    'KA': 'KA',
    'Kerala': 'KL',
    'KL': 'KL',
    'Ladakh': 'LA',
    'LA': 'LA',
    'Lakshadweep': 'LD',
    'LD': 'LD',
    'Madhya Pradesh': 'MP',
    'MP': 'MP',
    'Maharashtra': 'MH',
    'MH': 'MH',
    'Manipur': 'MN',
    'MN': 'MN',
    'Meghalaya': 'ML',
    'ML': 'ML',
    'Mizoram': 'MZ',
    'MZ': 'MZ',
    'Nagaland': 'NL',
    'NL': 'NL',
    'Odisha': 'OR',
    'OR': 'OR',
    'Puducherry': 'PY',
    'PY': 'PY',
    'Punjab': 'PB',
    'PB': 'PB',
    'Rajasthan': 'RJ',
    'RJ': 'RJ',
    'Sikkim': 'SK',
    'SK': 'SK',
    'Tamil Nadu': 'TN',
    'TN': 'TN',
    'Telangana': 'TG',
    'TG': 'TG',
    'Tripura': 'TR',
    'TR': 'TR',
    'Uttar Pradesh': 'UP',
    'UP': 'UP',
    'Uttarakhand': 'UK',
    'UK': 'UK',
    'West Bengal': 'WB',
    'WB': 'WB',

    # Italy
    'Abruzzo': 'AB',
    'AB': 'AB',
    'Aosta Valley': 'AO',
    'AO': 'AO',
    'Apulia': 'PU',
    'PU': 'PU',
    'Basilicata': 'BA',
    'BA': 'BA',
    'Calabria': 'CA',
    'CA': 'CA',
    'Campania': 'CM',
    'CM': 'CM',
    'Emilia-Romagna': 'ER',
    'ER': 'ER',
    'Friuli-Venezia Giulia': 'FV',
    'FV': 'FV',
    'Lazio': 'LA',
    'LA': 'LA',
    'Liguria': 'LI',
    'LI': 'LI',
    'Lombardy': 'LO',
    'LO': 'LO',
    'Marche': 'MA',
    'MA': 'MA',
    'Molise': 'MO',
    'MO': 'MO',
    'Piedmont': 'PI',
    'PI': 'PI',
    'Sardinia': 'SA',
    'SA': 'SA',
    'Sicily': 'SI',
    'SI': 'SI',
    'Trentino-South Tyrol': 'TN',
    'TN': 'TN',
    'Tuscany': 'TO',
    'TO': 'TO',
    'Umbria': 'UM',
    'UM': 'UM',
    'Veneto': 'VE',
    'VE': 'VE',

    # Japan
    'Aichi': '23',
    '23': '23',
    'Akita': '05',
    '05': '05',
    'Aomori': '02',
    '02': '02',
    'Chiba': '12',
    '12': '12',
    'Ehime': '38',
    '38': '38',
    'Fukui': '18',
    '18': '18',
    'Fukuoka': '40',
    '40': '40',
    'Fukushima': '07',
    '07': '07',
    'Gifu': '21',
    '21': '21',
    'Gunma': '10',
    '10': '10',
    'Hiroshima': '34',
    '34': '34',
    'Hokkaido': '01',
    '01': '01',
    'Hyogo': '28',
    '28': '28',
    'Ibaraki': '08',
    '08': '08',
    'Ishikawa': '17',
    '17': '17',
    'Iwate': '03',
    '03': '03',
    'Kagawa': '37',
    '37': '37',
    'Kagoshima': '46',
    '46': '46',
    'Kanagawa': '14',
    '14': '14',
    'Kochi': '39',
    '39': '39',
    'Kumamoto': '43',
    '43': '43',
    'Kyoto': '26',
    '26': '26',
    'Mie': '24',
    '24': '24',
    'Miyagi': '04',
    '04': '04',
    'Miyazaki': '45',
    '45': '45',
    'Nagano': '20',
    '20': '20',
    'Nagasaki': '42',
    '42': '42',
    'Nara': '29',
    '29': '29',
    'Niigata': '15',
    '15': '15',
    'Oita': '44',
    '44': '44',
    'Okayama': '33',
    '33': '33',
    'Okinawa': '47',
    '47': '47',
    'Osaka': '27',
    '27': '27',
    'Saga': '41',
    '41': '41',
    'Saitama': '11',
    '11': '11',
    'Shiga': '25',
    '25': '25',
    'Shimane': '32',
    '32': '32',
    'Shizuoka': '22',
    '22': '22',
    'Tochigi': '09',
    '09': '09',
    'Tokushima': '36',
    '36': '36',
    'Tokyo': '13',
    '13': '13',
    'Tottori': '31',
    '31': '31',
    'Toyama': '16',
    '16': '16',
    'Wakayama': '30',
    '30': '30',
    'Yamagata': '06',
    '06': '06',
    'Yamaguchi': '35',
    '35': '35',
    'Yamanashi': '19',
    '19': '19',

    # Mexico
    'Aguascalientes': 'AGU',
    'AGU': 'AGU',
    'Baja California': 'BCN',
    'BCN': 'BCN',
    'Baja California Sur': 'BCS',
    'BCS': 'BCS',
    'Campeche': 'CAM',
    'CAM': 'CAM',
    'Chiapas': 'CHP',
    'CHP': 'CHP',
    'Chihuahua': 'CHH',
    'CHH': 'CHH',
    'Coahuila': 'COA',
    'COA': 'COA',
    'Colima': 'COL',
    'COL': 'COL',
    'Durango': 'DUR',
    'DUR': 'DUR',
    'Guanajuato': 'GUA',
    'GUA': 'GUA',
    'Guerrero': 'GRO',
    'GRO': 'GRO',
    'Hidalgo': 'HID',
    'HID': 'HID',
    'Jalisco': 'JAL',
    'JAL': 'JAL',
    'México': 'MEX',
    'MEX': 'MEX',
    'Michoacán': 'MIC',
    'MIC': 'MIC',
    'Morelos': 'MOR',
    'MOR': 'MOR',
    'Nayarit': 'NAY',
    'NAY': 'NAY',
    'Nuevo León': 'NLE',
    'NLE': 'NLE',
    'Oaxaca': 'OAX',
    'OAX': 'OAX',
    'Puebla': 'PUE',
    'PUE': 'PUE',
    'Querétaro': 'QUE',
    'QUE': 'QUE',
    'Quintana Roo': 'ROO',
    'ROO': 'ROO',
    'San Luis Potosí': 'SLP',
    'SLP': 'SLP',
    'Sinaloa': 'SIN',
    'SIN': 'SIN',
    'Sonora': 'SON',
    'SON': 'SON',
    'Tabasco': 'TAB',
    'TAB': 'TAB',
    'Tamaulipas': 'TAM',
    'TAM': 'TAM',
    'Tlaxcala': 'TLA',
    'TLA': 'TLA',
    'Veracruz': 'VER',
    'VER': 'VER',
    'Yucatán': 'YUC',
    'YUC': 'YUC',
    'Zacatecas': 'ZAC',
    'ZAC': 'ZAC',

    # USA
    'Alabama': 'AL',
    'AL': 'AL',
    'Alaska': 'AK',
    'AK': 'AK',
    'Arizona': 'AZ',
    'AZ': 'AZ',
    'Arkansas': 'AR',
    'AR': 'AR',
    'California': 'CA',
    'CA': 'CA',
    'Colorado': 'CO',
    'CO': 'CO',
    'Connecticut': 'CT',
    'CT': 'CT',
    'Delaware': 'DE',
    'DE': 'DE',
    'District of Columbia': 'DC',
    'DC': 'DC',
    'Florida': 'FL',
    'FL': 'FL',
    'Georgia': 'GA',
    'GA': 'GA',
    'Hawaii': 'HI',
    'HI': 'HI',
    'Idaho': 'ID',
    'ID': 'ID',
    'Illinois': 'IL',
    'IL': 'IL',
    'Indiana': 'IN',
    'IN': 'IN',
    'Iowa': 'IA',
    'IA': 'IA',
    'Kansas': 'KS',
    'KS': 'KS',
    'Kentucky': 'KY',
    'KY': 'KY',
    'Louisiana': 'LA',
    'LA': 'LA',
    'Maine': 'ME',
    'ME': 'ME',
    'Maryland': 'MD',
    'MD': 'MD',
    'Massachusetts': 'MA',
    'MA': 'MA',
    'Michigan': 'MI',
    'MI': 'MI',
    'Minnesota': 'MN',
    'MN': 'MN',
    'Mississippi': 'MS',
    'MS': 'MS',
    'Missouri': 'MO',
    'MO': 'MO',
    'Montana': 'MT',
    'MT': 'MT',
    'Nebraska': 'NE',
    'NE': 'NE',
    'Nevada': 'NV',
    'NV': 'NV',
    'New Hampshire': 'NH',
    'NH': 'NH',
    'New Jersey': 'NJ',
    'NJ': 'NJ',
    'New Mexico': 'NM',
    'NM': 'NM',
    'New York': 'NY',
    'NY': 'NY',
    'North Carolina': 'NC',
    'NC': 'NC',
    'North Dakota': 'ND',
    'ND': 'ND',
    'Ohio': 'OH',
    'OH': 'OH',
    'Oklahoma': 'OK',
    'OK': 'OK',
    'Oregon': 'OR',
    'OR': 'OR',
    'Pennsylvania': 'PA',
    'PA': 'PA',
    'Rhode Island': 'RI',
    'RI': 'RI',
    'South Carolina': 'SC',
    'SC': 'SC',
    'South Dakota': 'SD',
    'SD': 'SD',
    'Tennessee': 'TN',
    'TN': 'TN',
    'Texas': 'TX',
    'TX': 'TX',
    'Utah': 'UT',
    'UT': 'UT',
    'Vermont': 'VT',
    'VT': 'VT',
    'Virginia': 'VA',
    'VA': 'VA',
    'Washington': 'WA',
    'WA': 'WA',
    'West Virginia': 'WV',
    'WV': 'WV',
    'Wisconsin': 'WI',
    'WI': 'WI',
    'Wyoming': 'WY',
    'WY': 'WY'
}
