COMMON_STATE_ALTERNATES = {
    'AUSTRALIAN CAPITAL TERRITORY': 'ACT',
    'ACT': 'ACT',
    'NEW SOUTH WALES': 'NSW',
    'NSW': 'NSW',
    'VICTORIA': 'VIC',
    'VIC': 'VIC',
    'QUEENSLAND': 'QLD',
    'QLD': 'QLD',
    'SOUTH AUSTRALIA': 'SA',
    'SA': 'SA',
    'WESTERN AUSTRALIA': 'WA',
    'WA': 'WA',
    'TASMANIA': 'TAS',
    'TAS': 'TAS',
    'NORTHERN TERRITORY': 'NT',
    'NT': 'NT',
    'ACRE': 'AC',
    'AC': 'AC',
    'ALAGOAS': 'AL',
    'AL': 'AL',
    'AMAPÁ': 'AP',
    'AP': 'AP',
    'AMAZONAS': 'AM',
    'AM': 'AM',
    'BAHIA': 'BA',
    'BA': 'BA',
    'CEARÁ': 'CE',
    'CE': 'CE',
    'DISTRITO FEDERAL': 'DF',
    'DF': 'DF',
    'ESPÍRITO SANTO': 'ES',
    'ES': 'ES',
    'GOIÁS': 'GO',
    'GO': 'GO',
    'MARANHÃO': 'MA',
    'MA': 'MA',
    'MATO GROSSO': 'MT',
    'MT': 'MT',
    'MATO GROSSO DO SUL': 'MS',
    'MS': 'MS',
    'MINAS GERAIS': 'MG',
    'MG': 'MG',
    'PARÁ': 'PA',
    'PA': 'PA',
    'PARAÍBA': 'PB',
    'PB': 'PB',
    'PARANÁ': 'PR',
    'PR': 'PR',
    'PERNAMBUCO': 'PE',
    'PE': 'PE',
    'PIAUÍ': 'PI',
    'PI': 'PI',
    'RIO DE JANEIRO': 'RJ',
    'RJ': 'RJ',
    'RIO GRANDE DO NORTE': 'RN',
    'RN': 'RN',
    'RIO GRANDE DO SUL': 'RS',
    'RS': 'RS',
    'RONDÔNIA': 'RO',
    'RO': 'RO',
    'RORAIMA': 'RR',
    'RR': 'RR',
    'SANTA CATARINA': 'SC',
    'SC': 'SC',
    'SÃO PAULO': 'SP',
    'SP': 'SP',
    'SERGIPE': 'SE',
    'SE': 'SE',
    'TOCANTINS': 'TO',
    'TO': 'TO',
    'ALBERTA': 'AB',
    'AB': 'AB',
    'BRITISH COLUMBIA': 'BC',
    'BC': 'BC',
    'MANITOBA': 'MB',
    'MB': 'MB',
    'NEW BRUNSWICK': 'NB',
    'NB': 'NB',
    'NEWFOUNDLAND AND LABRADOR': 'NL',
    'NL': 'NL',
    'NORTHWEST TERRITORIES': 'NT',
    'NOVA SCOTIA': 'NS',
    'NS': 'NS',
    'NUNAVUT': 'NU',
    'NU': 'NU',
    'ONTARIO': 'ON',
    'ON': 'ON',
    'PRINCE EDWARD ISLAND': 'PE',
    'QUEBEC': 'QC',
    'QC': 'QC',
    'SASKATCHEWAN': 'SK',
    'SK': 'SK',
    'YUKON': 'YT',
    'YT': 'YT',
    'BEIJING': 'BJ',
    'BJ': 'BJ',
    'TIANJIN': 'TJ',
    'TJ': 'TJ',
    'HEBEI': 'HE',
    'HE': 'HE',
    'SHANXI': 'SX',
    'SX': 'SX',
    'INNER MONGOLIA': 'NM',
    'NM': 'NM',
    'LIAONING': 'LN',
    'LN': 'LN',
    'JILIN': 'JL',
    'JL': 'JL',
    'HEILONGJIANG': 'HL',
    'HL': 'HL',
    'SHANGHAI': 'SH',
    'SH': 'SH',
    'JIANGSU': 'JS',
    'JS': 'JS',
    'ZHEJIANG': 'ZJ',
    'ZJ': 'ZJ',
    'ANHUI': 'AH',
    'AH': 'AH',
    'FUJIAN': 'FJ',
    'FJ': 'FJ',
    'JIANGXI': 'JX',
    'JX': 'JX',
    'SHANDONG': 'SD',
    'SD': 'SD',
    'HENAN': 'HA',
    'HA': 'HA',
    'HUBEI': 'HB',
    'HB': 'HB',
    'HUNAN': 'HN',
    'HN': 'HN',
    'GUANGDONG': 'GD',
    'GD': 'GD',
    'GUANGXI': 'GX',
    'GX': 'GX',
    'HAINAN': 'HI',
    'HI': 'HI',
    'CHONGQING': 'CQ',
    'CQ': 'CQ',
    'SICHUAN': 'SC',
    'GUIZHOU': 'GZ',
    'GZ': 'GZ',
    'YUNNAN': 'YN',
    'YN': 'YN',
    'TIBET': 'XZ',
    'XZ': 'XZ',
    'SHAANXI': 'SN',
    'SN': 'SN',
    'GANSU': 'GS',
    'GS': 'GS',
    'QINGHAI': 'QH',
    'QH': 'QH',
    'NINGXIA': 'NX',
    'NX': 'NX',
    'XINJIANG': 'XJ',
    'XJ': 'XJ',
    'TAIWAN': 'TW',
    'TW': 'TW',
    'HONG KONG': 'HK',
    'HK': 'HK',
    'MACAO': 'MO',
    'MO': 'MO',
    'CARLOW': 'CW',
    'CW': 'CW',
    'CAVAN': 'CN',
    'CN': 'CN',
    'CLARE': 'CE',
    'CORK': 'CO',
    'CO': 'CO',
    'DONEGAL': 'DL',
    'DL': 'DL',
    'DUBLIN': 'D',
    'D': 'D',
    'GALWAY': 'G',
    'G': 'G',
    'KERRY': 'KY',
    'KY': 'KY',
    'KILDARE': 'KE',
    'KE': 'KE',
    'KILKENNY': 'KK',
    'KK': 'KK',
    'LAOIS': 'LS',
    'LS': 'LS',
    'LEITRIM': 'LM',
    'LM': 'LM',
    'LIMERICK': 'LK',
    'LK': 'LK',
    'LONGFORD': 'LD',
    'LD': 'LD',
    'LOUTH': 'LH',
    'LH': 'LH',
    'MAYO': 'MO',
    'MEATH': 'MH',
    'MH': 'MH',
    'MONAGHAN': 'MN',
    'MN': 'MN',
    'OFFALY': 'OY',
    'OY': 'OY',
    'ROSCOMMON': 'RN',
    'SLIGO': 'SO',
    'SO': 'SO',
    'TIPPERARY': 'TA',
    'TA': 'TA',
    'WATERFORD': 'WD',
    'WD': 'WD',
    'WESTMEATH': 'WH',
    'WH': 'WH',
    'WEXFORD': 'WX',
    'WX': 'WX',
    'WICKLOW': 'WW',
    'WW': 'WW',
    'ANDAMAN AND NICOBAR ISLANDS': 'AN',
    'AN': 'AN',
    'ANDHRA PRADESH': 'AP',
    'ARUNACHAL PRADESH': 'AR',
    'AR': 'AR',
    'ASSAM': 'AS',
    'AS': 'AS',
    'BIHAR': 'BR',
    'BR': 'BR',
    'CHANDIGARH': 'CH',
    'CH': 'CH',
    'CHHATTISGARH': 'CT',
    'CT': 'CT',
    'DADRA AND NAGAR HAVELI AND DAMAN AND DIU': 'DD',
    'DD': 'DD',
    'DELHI': 'DL',
    'GOA': 'GA',
    'GA': 'GA',
    'GUJARAT': 'GJ',
    'GJ': 'GJ',
    'HARYANA': 'HR',
    'HR': 'HR',
    'HIMACHAL PRADESH': 'HP',
    'HP': 'HP',
    'JAMMU AND KASHMIR': 'JK',
    'JK': 'JK',
    'JHARKHAND': 'JH',
    'JH': 'JH',
    'KARNATAKA': 'KA',
    'KA': 'KA',
    'KERALA': 'KL',
    'KL': 'KL',
    'LADAKH': 'LA',
    'LA': 'LA',
    'LAKSHADWEEP': 'LD',
    'MADHYA PRADESH': 'MP',
    'MP': 'MP',
    'MAHARASHTRA': 'MH',
    'MANIPUR': 'MN',
    'MEGHALAYA': 'ML',
    'ML': 'ML',
    'MIZORAM': 'MZ',
    'MZ': 'MZ',
    'NAGALAND': 'NL',
    'ODISHA': 'OR',
    'OR': 'OR',
    'PUDUCHERRY': 'PY',
    'PY': 'PY',
    'PUNJAB': 'PB',
    'RAJASTHAN': 'RJ',
    'SIKKIM': 'SK',
    'TAMIL NADU': 'TN',
    'TN': 'TN',
    'TELANGANA': 'TG',
    'TG': 'TG',
    'TRIPURA': 'TR',
    'TR': 'TR',
    'UTTAR PRADESH': 'UP',
    'UP': 'UP',
    'UTTARAKHAND': 'UK',
    'UK': 'UK',
    'WEST BENGAL': 'WB',
    'WB': 'WB',
    'ABRUZZO': 'AB',
    'AOSTA VALLEY': 'AO',
    'AO': 'AO',
    'APULIA': 'PU',
    'PU': 'PU',
    'BASILICATA': 'BA',
    'CALABRIA': 'CA',
    'CA': 'CA',
    'CAMPANIA': 'CM',
    'CM': 'CM',
    'EMILIA-ROMAGNA': 'ER',
    'ER': 'ER',
    'FRIULI-VENEZIA GIULIA': 'FV',
    'FV': 'FV',
    'LAZIO': 'LA',
    'LIGURIA': 'LI',
    'LI': 'LI',
    'LOMBARDY': 'LO',
    'LO': 'LO',
    'MARCHE': 'MA',
    'MOLISE': 'MO',
    'PIEDMONT': 'PI',
    'SARDINIA': 'SA',
    'SICILY': 'SI',
    'SI': 'SI',
    'TRENTINO-SOUTH TYROL': 'TN',
    'TUSCANY': 'TO',
    'UMBRIA': 'UM',
    'UM': 'UM',
    'VENETO': 'VE',
    'VE': 'VE',
    'AICHI': '23',
    '23': '23',
    'AKITA': '05',
    '05': '05',
    'AOMORI': '02',
    '02': '02',
    'CHIBA': '12',
    '12': '12',
    'EHIME': '38',
    '38': '38',
    'FUKUI': '18',
    '18': '18',
    'FUKUOKA': '40',
    '40': '40',
    'FUKUSHIMA': '07',
    '07': '07',
    'GIFU': '21',
    '21': '21',
    'GUNMA': '10',
    '10': '10',
    'HIROSHIMA': '34',
    '34': '34',
    'HOKKAIDO': '01',
    '01': '01',
    'HYOGO': '28',
    '28': '28',
    'IBARAKI': '08',
    '08': '08',
    'ISHIKAWA': '17',
    '17': '17',
    'IWATE': '03',
    '03': '03',
    'KAGAWA': '37',
    '37': '37',
    'KAGOSHIMA': '46',
    '46': '46',
    'KANAGAWA': '14',
    '14': '14',
    'KOCHI': '39',
    '39': '39',
    'KUMAMOTO': '43',
    '43': '43',
    'KYOTO': '26',
    '26': '26',
    'MIE': '24',
    '24': '24',
    'MIYAGI': '04',
    '04': '04',
    'MIYAZAKI': '45',
    '45': '45',
    'NAGANO': '20',
    '20': '20',
    'NAGASAKI': '42',
    '42': '42',
    'NARA': '29',
    '29': '29',
    'NIIGATA': '15',
    '15': '15',
    'OITA': '44',
    '44': '44',
    'OKAYAMA': '33',
    '33': '33',
    'OKINAWA': '47',
    '47': '47',
    'OSAKA': '27',
    '27': '27',
    'SAGA': '41',
    '41': '41',
    'SAITAMA': '11',
    '11': '11',
    'SHIGA': '25',
    '25': '25',
    'SHIMANE': '32',
    '32': '32',
    'SHIZUOKA': '22',
    '22': '22',
    'TOCHIGI': '09',
    '09': '09',
    'TOKUSHIMA': '36',
    '36': '36',
    'TOKYO': '13',
    '13': '13',
    'TOTTORI': '31',
    '31': '31',
    'TOYAMA': '16',
    '16': '16',
    'WAKAYAMA': '30',
    '30': '30',
    'YAMAGATA': '06',
    '06': '06',
    'YAMAGUCHI': '35',
    '35': '35',
    'YAMANASHI': '19',
    '19': '19',
    'AGUASCALIENTES': 'AGU',
    'AGU': 'AGU',
    'BAJA CALIFORNIA': 'BCN',
    'BCN': 'BCN',
    'BAJA CALIFORNIA SUR': 'BCS',
    'BCS': 'BCS',
    'CAMPECHE': 'CAM',
    'CAM': 'CAM',
    'CHIAPAS': 'CHP',
    'CHP': 'CHP',
    'CHIHUAHUA': 'CHH',
    'CHH': 'CHH',
    'COAHUILA': 'COA',
    'COA': 'COA',
    'COLIMA': 'COL',
    'COL': 'COL',
    'DURANGO': 'DUR',
    'DUR': 'DUR',
    'GUANAJUATO': 'GUA',
    'GUA': 'GUA',
    'GUERRERO': 'GRO',
    'GRO': 'GRO',
    'HIDALGO': 'HID',
    'HID': 'HID',
    'JALISCO': 'JAL',
    'JAL': 'JAL',
    'MÉXICO': 'MEX',
    'MEX': 'MEX',
    'MICHOACÁN': 'MIC',
    'MIC': 'MIC',
    'MORELOS': 'MOR',
    'MOR': 'MOR',
    'NAYARIT': 'NAY',
    'NAY': 'NAY',
    'NUEVO LEÓN': 'NLE',
    'NLE': 'NLE',
    'OAXACA': 'OAX',
    'OAX': 'OAX',
    'PUEBLA': 'PUE',
    'PUE': 'PUE',
    'QUERÉTARO': 'QUE',
    'QUE': 'QUE',
    'QUINTANA ROO': 'ROO',
    'ROO': 'ROO',
    'SAN LUIS POTOSÍ': 'SLP',
    'SLP': 'SLP',
    'SINALOA': 'SIN',
    'SIN': 'SIN',
    'SONORA': 'SON',
    'SON': 'SON',
    'TABASCO': 'TAB',
    'TAB': 'TAB',
    'TAMAULIPAS': 'TAM',
    'TAM': 'TAM',
    'TLAXCALA': 'TLA',
    'TLA': 'TLA',
    'VERACRUZ': 'VER',
    'VER': 'VER',
    'YUCATÁN': 'YUC',
    'YUC': 'YUC',
    'ZACATECAS': 'ZAC',
    'ZAC': 'ZAC',
    'ALABAMA': 'AL',
    'ALASKA': 'AK',
    'AK': 'AK',
    'ARIZONA': 'AZ',
    'AZ': 'AZ',
    'ARKANSAS': 'AR',
    'CALIFORNIA': 'CA',
    'COLORADO': 'CO',
    'CONNECTICUT': 'CT',
    'DELAWARE': 'DE',
    'DE': 'DE',
    'DISTRICT OF COLUMBIA': 'DC',
    'DC': 'DC',
    'FLORIDA': 'FL',
    'FL': 'FL',
    'GEORGIA': 'GA',
    'HAWAII': 'HI',
    'IDAHO': 'ID',
    'ID': 'ID',
    'ILLINOIS': 'IL',
    'IL': 'IL',
    'INDIANA': 'IN',
    'IN': 'IN',
    'IOWA': 'IA',
    'IA': 'IA',
    'KANSAS': 'KS',
    'KS': 'KS',
    'KENTUCKY': 'KY',
    'LOUISIANA': 'LA',
    'MAINE': 'ME',
    'ME': 'ME',
    'MARYLAND': 'MD',
    'MD': 'MD',
    'MASSACHUSETTS': 'MA',
    'MICHIGAN': 'MI',
    'MI': 'MI',
    'MINNESOTA': 'MN',
    'MISSISSIPPI': 'MS',
    'MISSOURI': 'MO',
    'MONTANA': 'MT',
    'NEBRASKA': 'NE',
    'NE': 'NE',
    'NEVADA': 'NV',
    'NV': 'NV',
    'NEW HAMPSHIRE': 'NH',
    'NH': 'NH',
    'NEW JERSEY': 'NJ',
    'NJ': 'NJ',
    'NEW MEXICO': 'NM',
    'NEW YORK': 'NY',
    'NY': 'NY',
    'NORTH CAROLINA': 'NC',
    'NC': 'NC',
    'NORTH DAKOTA': 'ND',
    'ND': 'ND',
    'OHIO': 'OH',
    'OH': 'OH',
    'OKLAHOMA': 'OK',
    'OK': 'OK',
    'OREGON': 'OR',
    'PENNSYLVANIA': 'PA',
    'RHODE ISLAND': 'RI',
    'RI': 'RI',
    'SOUTH CAROLINA': 'SC',
    'SOUTH DAKOTA': 'SD',
    'TENNESSEE': 'TN',
    'TEXAS': 'TX',
    'TX': 'TX',
    'UTAH': 'UT',
    'UT': 'UT',
    'VERMONT': 'VT',
    'VT': 'VT',
    'VIRGINIA': 'VA',
    'VA': 'VA',
    'WASHINGTON': 'WA',
    'WEST VIRGINIA': 'WV',
    'WV': 'WV',
    'WISCONSIN': 'WI',
    'WI': 'WI',
    'WYOMING': 'WY',
    'WY': 'WY',
}
