COMMON_COUNTRY_ATERNATES = {
    'AFGHAN': 'AF',
    'ISLAMIC REPUBLIC OF AFGHANISTAN': 'AF',
    'AFGHANIA': 'AF',
    'AFGANESTAN': 'AF',
    'AFGHANESTAN': 'AF',
    'AFNISTN': 'AF',
    'AFNISTN ISLM JUMHORYAT': 'AF',
    'LAND': 'AX',
    'ALBANIAN': 'AL',
    'REPUBLIC OF ALBANIA': 'AL',
    'SHQIPRI': 'AL',
    'SHQIPRIA': 'AL',
    'SHQIPRIS': 'AL',
    'SHQIPRIS REPUBLIKA': 'AL',
    'ALGERIAN': 'DZ',
    'PEOPLES DEMOCRATIC REPUBLIC OF ALGERIA': 'DZ',
    'ALGRIE': 'DZ',
    'ALJUMHRIYYA ALJAZIRIYYA ADDMUQRIYYA ASHSHABYYA': 'DZ',
    'SAMOAN': 'WS',
    'TERRITORY OF AMERICAN SAMOA': 'AS',
    'ANDORRAN': 'AD',
    'PRINCIPALITY OF ANDORRA': 'AD',
    'PRINCIPAT DANDORRA': 'AD',
    'ANGOLAN': 'AO',
    'REPUBLIC OF ANGOLA': 'AO',
    'REPBLICA DE ANGOLA': 'AO',
    'ANGUILLAN': 'AI',
    'ANTIGUAN': 'AG',
    'BARBUDAN': 'AG',
    'ARGENTINE': 'AR',
    'REPUBLIC OF ARGENTINA': 'AR',
    'REPBLICA ARGENTINA': 'AR',
    'ARMENIAN': 'AM',
    'REPUBLIC OF ARMENIA': 'AM',
    'HAYASTAN': 'AM',
    'HAYASTANI HANRAPETUTYUN': 'AM',
    'ARUBAN': 'AW',
    'AUSTRALIAN': 'AU',
    'COMMONWEALTH OF AUSTRALIA': 'AU',
    'AUSTRIAN': 'AT',
    'REPUBLIC OF AUSTRIA': 'AT',
    'STERREICH': 'AT',
    'REPUBLIK STERREICH': 'AT',
    'AZERBAIJANI': 'AZ',
    'REPUBLIC OF AZERBAIJAN': 'AZ',
    'AZRBAYCAN': 'AZ',
    'AZRBAYCAN RESPUBLIKASI': 'AZ',
    'BAHAMIAN': 'BS',
    'COMMONWEALTH OF THE BAHAMAS': 'BS',
    'BAHRAINI': 'BH',
    'KINGDOM OF BAHRAIN': 'BH',
    'BANGLADESHI': 'BD',
    'PEOPLES REPUBLIC OF BANGLADESH': 'BD',
    'BANGLADESH': 'BD',
    'BARBADIAN': 'BB',
    'BELARUSIAN': 'BY',
    'REPUBLIC OF BELARUS': 'BY',
    'BELGIAN': 'BE',
    'KINGDOM OF BELGIUM': 'BE',
    'BELIZEAN': 'BZ',
    'REPUBLIC OF BELIZE': 'BZ',
    'BENINESE': 'BJ',
    'REPUBLIC OF BENIN': 'BJ',
    'BERMUDIAN': 'BM',
    'BHUTANESE': 'BT',
    'KINGDOM OF BHUTAN': 'BT',
    'BHUTAN': 'BT',
    'BOLIVIAN': 'BO',
    'PLURINATIONAL STATE OF BOLIVIA': 'BO',
    'BONAIRE SINT EUSTATIUS AND SABA': 'BQ',
    'BOSNIAN': 'BA',
    'REPUBLIC OF BOSNIA AND HERZEGOVINA': 'BA',
    'BOTSWANAN': 'BW',
    'REPUBLIC OF BOTSWANA': 'BW',
    'BOUVET ISLAND': 'BV',
    'BRAZILIAN': 'BR',
    'FEDERATIVE REPUBLIC OF BRAZIL': 'BR',
    'BRITISH INDIAN OCEAN TERRITORY': 'IO',
    'BRUNEI DARUSSALAM': 'BN',
    'NATION OF BRUNEI THE ABODE OF PEACE': 'BN',
    'BULGARIAN': 'BG',
    'REPUBLIC OF BULGARIA': 'BG',
    'BURKINAB': 'BF',
    'BURKINA FASO': 'BF',
    'BURUNDI': 'BI',
    'KINGDOM OF BURUNDI': 'BI',
    'CABO VERDEAN': 'CV',
    'REPUBLIC OF CABO VERDE': 'CV',
    'CAMBODIAN': 'KH',
    'KINGDOM OF CAMBODIA': 'KH',
    'CAMEROONIAN': 'CM',
    'REPUBLIC OF CAMEROON': 'CM',
    'CANADIAN': 'CA',
    'CAYMANIAN': 'KY',
    'CENTRAL AFRICAN': 'CF',
    'CENTRAL AFRICAN REPUBLIC': 'CF',
    'CHADIAN': 'TD',
    'REPUBLIC OF CHAD': 'TD',
    'CHILEAN': 'CL',
    'REPUBLIC OF CHILE': 'CL',
    'CHINESE': 'CN',
    'PEOPLES REPUBLIC OF CHINA': 'CN',
    'CHRISTMAS ISLAND': 'CX',
    'COCOS KEELING ISLANDS': 'CC',
    'COLOMBIAN': 'CO',
    'REPUBLIC OF COLOMBIA': 'CO',
    'COMORIAN': 'KM',
    'UNION OF THE COMOROS': 'KM',
    'CONGOLESE': 'CG',
    'DEMOCRATIC REPUBLIC OF THE CONGO': 'CD',
    'CONGO': 'CG',
    'COOK ISLANDER': 'CK',
    'COSTA RICAN': 'CR',
    'REPUBLIC OF COSTA RICA': 'CR',
    'CTE DIVOIRE': 'CI',
    'REPUBLIC OF CTE DIVOIRE': 'CI',
    'IVORIAN': 'CI',
    'CROATIAN': 'HR',
    'REPUBLIC OF CROATIA': 'HR',
    'CUBAN': 'CU',
    'REPUBLIC OF CUBA': 'CU',
    'CURAAO': 'CW',
    'CYPRIOT': 'CY',
    'REPUBLIC OF CYPRUS': 'CY',
    'CZECH': 'CZ',
    'CZECH REPUBLIC': 'CZ',
    'DENMARK': 'DK',
    'KINGDOM OF DENMARK': 'DK',
    'DJIBOUTIAN': 'DJ',
    'REPUBLIC OF DJIBOUTI': 'DJ',
    'DOMINICAN': 'DO',
    'DOMINICAN REPUBLIC': 'DO',
    'ECUADORIAN': 'EC',
    'REPUBLIC OF ECUADOR': 'EC',
    'EGYPTIAN': 'EG',
    'ARAB REPUBLIC OF EGYPT': 'EG',
    'EL SALVADORIAN': 'SV',
    'REPUBLIC OF EL SALVADOR': 'SV',
    'EQUATORIAL GUINEAN': 'GQ',
    'REPUBLIC OF EQUATORIAL GUINEA': 'GQ',
    'ERITREAN': 'ER',
    'STATE OF ERITREA': 'ER',
    'ESTONIAN': 'EE',
    'REPUBLIC OF ESTONIA': 'EE',
    'ESWATINI': 'SZ',
    'KINGDOM OF ESWATINI': 'SZ',
    'ETHIOPIAN': 'ET',
    'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA': 'ET',
    'FALKLAND ISLANDER': 'FK',
    'FAROESE': 'FO',
    'FAROE ISLANDS': 'FO',
    'FIJIAN': 'FJ',
    'REPUBLIC OF FIJI': 'FJ',
    'FINNISH': 'FI',
    'REPUBLIC OF FINLAND': 'FI',
    'FRANCE': 'FR',
    'FRENCH': 'FR',
    'FRENCH GUIANESE': 'GF',
    'FRENCH POLYNESIAN': 'PF',
    'FRENCH SOUTHERN TERRITORIES': 'TF',
    'GABONESE': 'GA',
    'GABON': 'GA',
    'REPUBLIC OF GABON': 'GA',
    'GAMBIAN': 'GM',
    'REPUBLIC OF THE GAMBIA': 'GM',
    'GEORGIAN': 'GE',
    'GERMANY': 'DE',
    'GHANAIAN': 'GH',
    'REPUBLIC OF GHANA': 'GH',
    'GIBRALTAR': 'GI',
    'HELLENIC REPUBLIC': 'GR',
    'GREECE': 'GR',
    'GREENLANDIC': 'GL',
    'GREENLAND': 'GL',
    'GRENADIAN': 'GD',
    'GRENADA': 'GD',
    'GUADELOUPE': 'GP',
    'GUADELOUPEAN': 'GP',
    'GUAMANIAN': 'GU',
    'GUAM': 'GU',
    'GUATEMALAN': 'GT',
    'REPUBLIC OF GUATEMALA': 'GT',
    'GUERNSEY': 'GG',
    'BAILIWICK OF GUERNSEY': 'GG',
    'GUINEABISSAUAN': 'GW',
    'ENG': 'GB',
    'ENGLAND': 'GB',
    'REPUBLIC OF GUINEABISSAU': 'GW',
    'GUINEA': 'GN',
    'REPUBLIC OF GUINEA': 'GN',
    'GUYANESE': 'GY',
    'COOPERATIVE REPUBLIC OF GUYANA': 'GY',
    'HAITIAN': 'HT',
    'REPUBLIC OF HAITI': 'HT',
    'HEARD ISLAND AND MCDONALD ISLANDS': 'HM',
    'HOLY SEE': 'VA',
    'HONDURAN': 'HN',
    'REPUBLIC OF HONDURAS': 'HN',
    'HONG KONG': 'HK',
    'KOWLOON': 'HK',
    'HONG KONG SPECIAL ADMINISTRATIVE REGION': 'HK',
    'HUNGARIAN': 'HU',
    'HUNGARY': 'HU',
    'ICELANDIC': 'IS',
    'ICELAND': 'IS',
    'REPUBLIC OF ICELAND': 'IS',
    'INDIAN': 'IN',
    'REPUBLIC OF INDIA': 'IN',
    'INDONESIAN': 'ID',
    'REPUBLIC OF INDONESIA': 'ID',
    'IRANIAN': 'IR',
    'ISLAMIC REPUBLIC OF IRAN': 'IR',
    'IRAQI': 'IQ',
    'REPUBLIC OF IRAQ': 'IQ',
    'IRELAND': 'IE',
    'ISLE OF MAN': 'IM',
    'ISRAELI': 'IL',
    'STATE OF ISRAEL': 'IL',
    'ITALY': 'IT',
    'ITALIAN': 'IT',
    'JAMAICAN': 'JM',
    'JAPAN': 'JP',
    'JERSEY': 'JE',
    'JERSEY BAILIWICK OF': 'JE',
    'JORDANIAN': 'JO',
    'HASHEMITE KINGDOM OF JORDAN': 'JO',
    'KAZAKH': 'KZ',
    'REPUBLIC OF KAZAKHSTAN': 'KZ',
    'KENYAN': 'KE',
    'REPUBLIC OF KENYA': 'KE',
    'KIRIBATI': 'KI',
    'REPUBLIC OF KIRIBATI': 'KI',
    'DEMOCRATIC PEOPLES REPUBLIC OF KOREA': 'KP',
    'KOREA DEMOCRATIC PEOPLES REPUBLIC OF': 'KP',
    'NORTH KOREA': 'KP',
    'REPUBLIC OF KOREA': 'KR',
    'KOREA REPUBLIC OF': 'KR',
    'SOUTH KOREA': 'KR',
    'KUWAITI': 'KW',
    'STATE OF KUWAIT': 'KW',
    'KYRGYZSTANI': 'KG',
    'KYRGYZ REPUBLIC': 'KG',
    'LAO PEOPLES DEMOCRATIC REPUBLIC': 'LA',
    'LAO': 'LA',
    'LAOS': 'LA',
    'LATVIAN': 'LV',
    'REPUBLIC OF LATVIA': 'LV',
    'LEBANESE': 'LB',
    'LEBANON': 'LB',
    'REPUBLIC OF LEBANON': 'LB',
    'MOSOTHO': 'LS',
    'KINGDOM OF LESOTHO': 'LS',
    'LESOTHO': 'LS',
    'LIBERIAN': 'LR',
    'REPUBLIC OF LIBERIA': 'LR',
    'LIBYAN': 'LY',
    'LIBYA': 'LY',
    'STATE OF LIBYA': 'LY',
    'LIECHTENSTEIN': 'LI',
    'PRINCIPALITY OF LIECHTENSTEIN': 'LI',
    'LITHUANIAN': 'LT',
    'REPUBLIC OF LITHUANIA': 'LT',
    'LUXEMBOURG': 'LU',
    'GRAND DUCHY OF LUXEMBOURG': 'LU',
    'MACAO': 'MO',
    'MACAO SPECIAL ADMINISTRATIVE REGION': 'MO',
    'MACEDONIAN': 'MK',
    'REPUBLIC OF NORTH MACEDONIA': 'MK',
    'MADAGASCAR': 'MG',
    'MALAWIAN': 'MW',
    'REPUBLIC OF MALAWI': 'MW',
    'MALAYSIAN': 'MY',
    'MALAYSIA': 'MY',
    'MALDIVIAN': 'MV',
    'REPUBLIC OF MALDIVES': 'MV',
    'UK': 'GB',
    'MALIAN': 'ML',
    'REPUBLIC OF MALI': 'ML',
    'MALTA': 'MT',
    'REPUBLIC OF MALTA': 'MT',
    'MARSHALL ISLANDS': 'MH',
    'REPUBLIC OF THE MARSHALL ISLANDS': 'MH',
    'MARTINICAN': 'MQ',
    'MAURITANIAN': 'MR',
    'ISLAMIC REPUBLIC OF MAURITANIA': 'MR',
    'MAURITIUS': 'MU',
    'REPUBLIC OF MAURITIUS': 'MU',
    'MAYOTTE': 'YT',
    'MEXICO': 'MX',
    'UNITED MEXICAN STATES': 'MX',
    'MICRONESIAN': 'FM',
    'FEDERATED STATES OF MICRONESIA': 'FM',
    'MOLDOVAN': 'MD',
    'REPUBLIC OF MOLDOVA': 'MD',
    'MONACO': 'MC',
    'MONGOLIAN': 'MN',
    'MONTENEGRIN': 'ME',
    'MONTENEGRO': 'ME',
    'MONTSERRAT': 'MS',
    'MOROCCAN': 'MA',
    'KINGDOM OF MOROCCO': 'MA',
    'MOZAMBICAN': 'MZ',
    'REPUBLIC OF MOZAMBIQUE': 'MZ',
    'MYANMA': 'MM',
    'REPUBLIC OF THE UNION OF MYANMAR': 'MM',
    'NAMIBIAN': 'NA',
    'REPUBLIC OF NAMIBIA': 'NA',
    'NAURUAN': 'NR',
    'REPUBLIC OF NAURU': 'NR',
    'NEPALI': 'NP',
    'FEDERAL DEMOCRATIC REPUBLIC OF NEPAL': 'NP',
    'NEPAL': 'NP',
    'DUTCH': 'NL',
    'KINGDOM OF THE NETHERLANDS': 'NL',
    'NETHERLANDS': 'NL',
    'NEW CALEDONIAN': 'NC',
    'NEW ZEALAND': 'NZ',
    'NICARAGUAN': 'NI',
    'REPUBLIC OF NICARAGUA': 'NI',
    'NIGERIEN': 'NE',
    'REPUBLIC OF THE NIGER': 'NE',
    'NIGER': 'NE',
    'NIGERIAN': 'NG',
    'FEDERAL REPUBLIC OF NIGERIA': 'NG',
    'NIGERIA': 'NG',
    'NIUEAN': 'NU',
    'NORFOLK ISLAND': 'NF',
    'NORWEGIAN': 'NO',
    'KINGDOM OF NORWAY': 'NO',
    'OMANI': 'OM',
    'SULTANATE OF OMAN': 'OM',
    'PAKISTANI': 'PK',
    'ISLAMIC REPUBLIC OF PAKISTAN': 'PK',
    'PAKISTAN': 'PK',
    'PALAUAN': 'PW',
    'REPUBLIC OF PALAU': 'PW',
    'PALESTINIAN': 'PS',
    'STATE OF PALESTINE': 'PS',
    'PANAMANIAN': 'PA',
    'REPUBLIC OF PANAMA': 'PA',
    'PAPUA NEW GUINEAN': 'PG',
    'INDEPENDENT STATE OF PAPUA NEW GUINEA': 'PG',
    'PARAGUAYAN': 'PY',
    'REPUBLIC OF PARAGUAY': 'PY',
    'PERUVIAN': 'PE',
    'REPUBLIC OF PERU': 'PE',
    'FILIPINO': 'PH',
    'REPUBLIC OF THE PHILIPPINES': 'PH',
    'PITCAIRN ISLANDER': 'PN',
    'POLISH': 'PL',
    'REPUBLIC OF POLAND': 'PL',
    'PORTUGUESE': 'PT',
    'PORTUGUESE REPUBLIC': 'PT',
    'PUERTO RICAN': 'PR',
    'COMMONWEALTH OF PUERTO RICO': 'PR',
    'QATARI': 'QA',
    'STATE OF QATAR': 'QA',
    'RUNIONESE': 'RE',
    'RUNION': 'RE',
    'ROMANIAN': 'RO',
    'RUSSIAN': 'RU',
    'RUSSIAN FEDERATION': 'RU',
    'RWANDAN': 'RW',
    'REPUBLIC OF RWANDA': 'RW',
    'SAINT BARTHLEMY': 'BL',
    'SAINT HELENIAN': 'SH',
    'SAINT KITTS AND NEVIS': 'KN',
    'SAINT LUCIA': 'LC',
    'SAINT MARTIN': 'MF',
    'SAINT PIERRE AND MIQUELON': 'PM',
    'SAINT VINCENT AND THE GRENADINES': 'VC',
    'SAINT VINCENT AND GRENADINES': 'VC',
    'ST VINCENT AND THE GRENADINES': 'VC',
    'ST VINCENT AND GRENADINES': 'VC',
    'GRENADINES': 'VC',
    'INDEPENDENT STATE OF SAMOA': 'WS',
    'SAN MARINESE': 'SM',
    'REPUBLIC OF SAN MARINO': 'SM',
    'SAO TOMEAN': 'ST',
    'DEMOCRATIC REPUBLIC OF SAO TOME AND PRINCIPE': 'ST',
    'SAUDI ARABIAN': 'SA',
    'KINGDOM OF SAUDI ARABIA': 'SA',
    'SENEGALESE': 'SN',
    'REPUBLIC OF SENEGAL': 'SN',
    'SERBIAN': 'RS',
    'REPUBLIC OF SERBIA': 'RS',
    'SEYCHELLOIS': 'SC',
    'REPUBLIC OF SEYCHELLES': 'SC',
    'SIERRA LEONEAN': 'SL',
    'REPUBLIC OF SIERRA LEONE': 'SL',
    'SINGAPOREAN': 'SG',
    'REPUBLIC OF SINGAPORE': 'SG',
    'SINT MAARTEN': 'SX',
    'SLOVAK': 'SK',
    'SLOVAK REPUBLIC': 'SK',
    'SLOVENE': 'SI',
    'REPUBLIC OF SLOVENIA': 'SI',
    'SOLOMON ISLANDER': 'SB',
    'SOMALI': 'SO',
    'FEDERAL REPUBLIC OF SOMALIA': 'SO',
    'SOUTH AFRICAN': 'ZA',
    'REPUBLIC OF SOUTH AFRICA': 'ZA',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'GS',
    'SOUTH SUDANESE': 'SS',
    'SPAIN': 'ES',
    'SPANISH': 'ES',
    'SRI LANKAN': 'LK',
    'DEMOCRATIC SOCIALIST REPUBLIC OF SRI LANKA': 'LK',
    'SUDANESE': 'SD',
    'REPUBLIC OF THE SUDAN': 'SD',
    'SURINAMESE': 'SR',
    'REPUBLIC OF SURINAME': 'SR',
    'SVALBARD': 'SJ',
    'SWAZI': 'SZ',
    'KINGDOM OF SWAZILAND': 'SZ',
    'SWEDEN': 'SE',
    'SWEDISH': 'SE',
    'KINGDOM OF SWEDEN': 'SE',
    'SWISS': 'CH',
    'SWISS CONFEDERATION': 'CH',
    'SWITZERLAND': 'CH',
    'SUISSE': 'CH',
    'SYRIAN': 'SY',
    'SYRIAN ARAB REPUBLIC': 'SY',
    'REPUBLIC OF CHINA': 'TW',
    'TAIWAN': 'TW',
    'TAJIK': 'TJ',
    'REPUBLIC OF TAJIKISTAN': 'TJ',
    'TANZANIAN': 'TZ',
    'UNITED REPUBLIC OF TANZANIA': 'TZ',
    'THAILAND': 'TH',
    'KINGDOM OF THAILAND': 'TH',
    'EAST TIMORESE': 'TL',
    'DEMOCRATIC REPUBLIC OF TIMORLESTE': 'TL',
    'TOGOLESE': 'TG',
    'TOGOLESE REPUBLIC': 'TG',
    'TOKELAUAN': 'TK',
    'TONGAN': 'TO',
    'KINGDOM OF TONGA': 'TO',
    'TRINIDADIAN': 'TT',
    'TOBAGONIAN': 'TT',
    'REPUBLIC OF TRINIDAD AND TOBAGO': 'TT',
    'TUNISIAN': 'TN',
    'REPUBLIC OF TUNISIA': 'TN',
    'TURKISH': 'TR',
    'REPUBLIC OF TURKEY': 'TR',
    'TURKMEN': 'TM',
    'TURKMENISTAN': 'TM',
    'TURKS AND CAICOS ISLANDER': 'TC',
    'TUVALUAN': 'TV',
    'REPUBLIC OF TUVALU': 'TV',
    'UGANDAN': 'UG',
    'REPUBLIC OF UGANDA': 'UG',
    'UKRAINIAN': 'UA',
    'UKRAINE': 'UA',
    'UKRAINA': 'UA',
    'UNITED ARAB EMIRATES': 'AE',
    'UNITED KINGDOM': 'GB',
    'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND': 'GB',
    'UNITED STATES': 'US',
    'UNITED STATES OF AMERICA': 'US',
    'UNITED STATES MINOR OUTLYING ISLANDS': 'UM',
    'URUGUAYAN': 'UY',
    'ORIENTAL REPUBLIC OF URUGUAY': 'UY',
    'UZBEK': 'UZ',
    'REPUBLIC OF UZBEKISTAN': 'UZ',
    'NIVANUATU': 'VU',
    'REPUBLIC OF VANUATU': 'VU',
    'VENEZUELAN': 'VE',
    'BOLIVARIAN REPUBLIC OF VENEZUELA': 'VE',
    'VIETNAMESE': 'VN',
    'SOCIALIST REPUBLIC OF VIETNAM': 'VN',
    'VIET NAM': 'VN',
    'BRITISH VIRGIN ISLANDER': 'VG',
    'VIRGIN ISLANDS BRITISH': 'VG',
    'US VIRGIN ISLANDER': 'VI',
    'VIRGIN ISLANDS US': 'VI',
    'WALLIS AND FUTUNA': 'WF',
    'WESTERN SAHARA': 'EH',
    'YEMENI': 'YE',
    'TAOYUAN': 'TW',
    'USOFAMERICA': 'US',
    'REPUBLIC OF YEMEN': 'YE',
    'ZAMBIAN': 'ZM',
    'REPUBLIC OF ZAMBIA': 'ZM',
    'ZIMBABWEAN': 'ZW',
    'DEUTSCHLAND': 'DE',
    'REPUBLIC OF ZIMBABWE': 'ZW',
    'US of A': 'US',
    'AFG': 'AF',
    'ALA': 'AX',
    'ALB': 'AL',
    'DZA': 'DZ',
    'ASM': 'AS',
    'AND': 'AD',
    'AGO': 'AO',
    'AIA': 'AI',
    'ATA': 'AQ',
    'ATG': 'AG',
    'ARG': 'AR',
    'ARM': 'AM',
    'ABW': 'AW',
    'AUS': 'AU',
    'AUT': 'AT',
    'AZE': 'AZ',
    'BHS': 'BS',
    'BHR': 'BH',
    'BGD': 'BD',
    'BRB': 'BB',
    'BLR': 'BY',
    'BEL': 'BE',
    'BLZ': 'BZ',
    'BEN': 'BJ',
    'BMU': 'BM',
    'BTN': 'BT',
    'BOL': 'BO',
    'BES': 'BQ',
    'BIH': 'BA',
    'BWA': 'BW',
    'BVT': 'BV',
    'BRA': 'BR',
    'IOT': 'IO',
    'BRN': 'BN',
    'BGR': 'BG',
    'BFA': 'BF',
    'BDI': 'BI',
    'CPV': 'CV',
    'KHM': 'KH',
    'CMR': 'CM',
    'CAN': 'CA',
    'CYM': 'KY',
    'CAF': 'CF',
    'TCD': 'TD',
    'CHL': 'CL',
    'CHN': 'CN',
    'CXR': 'CX',
    'CCK': 'CC',
    'COL': 'CO',
    'COM': 'KM',
    'COG': 'CG',
    'COD': 'CD',
    'COK': 'CK',
    'CRI': 'CR',
    'CIV': 'CI',
    'HRV': 'HR',
    'CUB': 'CU',
    'CUW': 'CW',
    'CYP': 'CY',
    'CZE': 'CZ',
    'DNK': 'DK',
    'DJI': 'DJ',
    'DMA': 'DM',
    'DOM': 'DO',
    'ECU': 'EC',
    'EGY': 'EG',
    'SLV': 'SV',
    'GNQ': 'GQ',
    'ERI': 'ER',
    'EST': 'EE',
    'SWZ': 'SZ',
    'ETH': 'ET',
    'FLK': 'FK',
    'FRO': 'FO',
    'FJI': 'FJ',
    'FIN': 'FI',
    'FRA': 'FR',
    'GUF': 'GF',
    'PYF': 'PF',
    'ATF': 'TF',
    'GAB': 'GA',
    'GMB': 'GM',
    'GEO': 'GE',
    'DEU': 'DE',
    'GHA': 'GH',
    'GIB': 'GI',
    'GRC': 'GR',
    'GRL': 'GL',
    'GRD': 'GD',
    'GLP': 'GP',
    'GUM': 'GU',
    'GTM': 'GT',
    'GGY': 'GG',
    'GIN': 'GN',
    'GNB': 'GW',
    'GUY': 'GY',
    'HTI': 'HT',
    'HMD': 'HM',
    'VAT': 'VA',
    'HND': 'HN',
    'HKG': 'HK',
    'HUN': 'HU',
    'ISL': 'IS',
    'IND': 'IN',
    'IDN': 'ID',
    'IRN': 'IR',
    'IRQ': 'IQ',
    'IRL': 'IE',
    'IMN': 'IM',
    'ISR': 'IL',
    'ITA': 'IT',
    'JAM': 'JM',
    'JPN': 'JP',
    'JEY': 'JE',
    'JOR': 'JO',
    'KAZ': 'KZ',
    'KEN': 'KE',
    'KIR': 'KI',
    'PRK': 'KP',
    'KOR': 'KR',
    'KWT': 'KW',
    'KGZ': 'KG',
    'LVA': 'LV',
    'LBN': 'LB',
    'LSO': 'LS',
    'LBR': 'LR',
    'LBY': 'LY',
    'LIE': 'LI',
    'LTU': 'LT',
    'LUX': 'LU',
    'MAC': 'MO',
    'MDG': 'MG',
    'MWI': 'MW',
    'MYS': 'MY',
    'MDV': 'MV',
    'MLI': 'ML',
    'MLT': 'MT',
    'MHL': 'MH',
    'MTQ': 'MQ',
    'MRT': 'MR',
    'MUS': 'MU',
    'MYT': 'YT',
    'MEX': 'MX',
    'FSM': 'FM',
    'MDA': 'MD',
    'MCO': 'MC',
    'MNG': 'MN',
    'MNE': 'ME',
    'MSR': 'MS',
    'MAR': 'MA',
    'MOZ': 'MZ',
    'MMR': 'MM',
    'NAM': 'NA',
    'NRU': 'NR',
    'NPL': 'NP',
    'NLD': 'NL',
    'NCL': 'NC',
    'NZL': 'NZ',
    'NIC': 'NI',
    'NER': 'NE',
    'NGA': 'NG',
    'NIU': 'NU',
    'NFK': 'NF',
    'MKD': 'MK',
    'MNP': 'MP',
    'NOR': 'NO',
    'OMN': 'OM',
    'PAK': 'PK',
    'PLW': 'PW',
    'PSE': 'PS',
    'PAN': 'PA',
    'PNG': 'PG',
    'PRY': 'PY',
    'PER': 'PE',
    'PHL': 'PH',
    'PCN': 'PN',
    'POL': 'PL',
    'PRT': 'PT',
    'PRI': 'PR',
    'QAT': 'QA',
    'REU': 'RE',
    'ROU': 'RO',
    'RUS': 'RU',
    'RWA': 'RW',
    'BLM': 'BL',
    'SHN': 'SH',
    'KNA': 'KN',
    'LCA': 'LC',
    'MAF': 'MF',
    'SPM': 'PM',
    'VCT': 'VC',
    'WSM': 'WS',
    'SMR': 'SM',
    'STP': 'ST',
    'SAU': 'SA',
    'SEN': 'SN',
    'SRB': 'RS',
    'SYC': 'SC',
    'SLE': 'SL',
    'SGP': 'SG',
    'SXM': 'SX',
    'SVK': 'SK',
    'SVN': 'SI',
    'SLB': 'SB',
    'SOM': 'SO',
    'ZAF': 'ZA',
    'SGS': 'GS',
    'SSD': 'SS',
    'ESP': 'ES',
    'LKA': 'LK',
    'SDN': 'SD',
    'SUR': 'SR',
    'SJM': 'SJ',
    'SWE': 'SE',
    'CHE': 'CH',
    'SYR': 'SY',
    'TWN': 'TW',
    'TJK': 'TJ',
    'TZA': 'TZ',
    'THA': 'TH',
    'TLS': 'TL',
    'TGO': 'TG',
    'TKL': 'TK',
    'TON': 'TO',
    'TTO': 'TT',
    'TUN': 'TN',
    'TUR': 'TR',
    'TKM': 'TM',
    'TCA': 'TC',
    'TUV': 'TV',
    'UGA': 'UG',
    'UKR': 'UA',
    'ARE': 'AE',
    'GBR': 'GB',
    'USA': 'US',
    'UMI': 'UM',
    'URY': 'UY',
    'UZB': 'UZ',
    'VUT': 'VU',
    'VEN': 'VE',
    'VNM': 'VN',
    'VGB': 'VG',
    'VIR': 'VI',
    'WLF': 'WF',
    'ESH': 'EH',
    'YEM': 'YE',
    'ZMB': 'ZM',
    'ZWE': 'ZW',
    'AF': 'AF',
    'AX': 'AX',
    'AL': 'AL',
    'DZ': 'DZ',
    'AS': 'AS',
    'AD': 'AD',
    'AO': 'AO',
    'AI': 'AI',
    'AQ': 'AQ',
    'AG': 'AG',
    'AR': 'AR',
    'AM': 'AM',
    'AW': 'AW',
    'AU': 'AU',
    'AT': 'AT',
    'AZ': 'AZ',
    'BS': 'BS',
    'BH': 'BH',
    'BD': 'BD',
    'BB': 'BB',
    'BY': 'BY',
    'BE': 'BE',
    'BZ': 'BZ',
    'BJ': 'BJ',
    'BM': 'BM',
    'BT': 'BT',
    'BO': 'BO',
    'BQ': 'BQ',
    'BA': 'BA',
    'BW': 'BW',
    'BV': 'BV',
    'BR': 'BR',
    'IO': 'IO',
    'BN': 'BN',
    'BG': 'BG',
    'BF': 'BF',
    'BI': 'BI',
    'CV': 'CV',
    'KH': 'KH',
    'CM': 'CM',
    'CA': 'CA',
    'KY': 'KY',
    'CF': 'CF',
    'TD': 'TD',
    'CL': 'CL',
    'CN': 'CN',
    'CX': 'CX',
    'CC': 'CC',
    'CO': 'CO',
    'KM': 'KM',
    'CG': 'CG',
    'CD': 'CD',
    'CK': 'CK',
    'CR': 'CR',
    'CI': 'CI',
    'HR': 'HR',
    'CU': 'CU',
    'CW': 'CW',
    'CY': 'CY',
    'CZ': 'CZ',
    'DK': 'DK',
    'DJ': 'DJ',
    'DM': 'DM',
    'DO': 'DO',
    'EC': 'EC',
    'EG': 'EG',
    'SV': 'SV',
    'GQ': 'GQ',
    'ER': 'ER',
    'EE': 'EE',
    'SZ': 'SZ',
    'ET': 'ET',
    'FK': 'FK',
    'FO': 'FO',
    'FJ': 'FJ',
    'FI': 'FI',
    'FR': 'FR',
    'GF': 'GF',
    'PF': 'PF',
    'TF': 'TF',
    'GA': 'GA',
    'GM': 'GM',
    'GE': 'GE',
    'DE': 'DE',
    'GH': 'GH',
    'GI': 'GI',
    'GR': 'GR',
    'GL': 'GL',
    'GD': 'GD',
    'GP': 'GP',
    'GU': 'GU',
    'GT': 'GT',
    'GG': 'GG',
    'GN': 'GN',
    'GW': 'GW',
    'GY': 'GY',
    'HT': 'HT',
    'HM': 'HM',
    'VA': 'VA',
    'HN': 'HN',
    'HK': 'HK',
    'HU': 'HU',
    'IS': 'IS',
    'IN': 'IN',
    'ID': 'ID',
    'IR': 'IR',
    'IQ': 'IQ',
    'IE': 'IE',
    'IM': 'IM',
    'IL': 'IL',
    'IT': 'IT',
    'JM': 'JM',
    'JP': 'JP',
    'JE': 'JE',
    'JO': 'JO',
    'KZ': 'KZ',
    'KE': 'KE',
    'KI': 'KI',
    'KP': 'KP',
    'KR': 'KR',
    'KW': 'KW',
    'KG': 'KG',
    'LA': 'LA',
    'LV': 'LV',
    'LB': 'LB',
    'LS': 'LS',
    'LR': 'LR',
    'LY': 'LY',
    'LI': 'LI',
    'LT': 'LT',
    'LU': 'LU',
    'MO': 'MO',
    'MG': 'MG',
    'MW': 'MW',
    'MY': 'MY',
    'MV': 'MV',
    'ML': 'ML',
    'MT': 'MT',
    'MH': 'MH',
    'MQ': 'MQ',
    'MR': 'MR',
    'MU': 'MU',
    'YT': 'YT',
    'MX': 'MX',
    'FM': 'FM',
    'MD': 'MD',
    'MC': 'MC',
    'MN': 'MN',
    'ME': 'ME',
    'MS': 'MS',
    'MA': 'MA',
    'MZ': 'MZ',
    'MM': 'MM',
    'NA': 'NA',
    'NR': 'NR',
    'NP': 'NP',
    'NL': 'NL',
    'NC': 'NC',
    'NZ': 'NZ',
    'NI': 'NI',
    'NE': 'NE',
    'NG': 'NG',
    'NU': 'NU',
    'NF': 'NF',
    'MK': 'MK',
    'MP': 'MP',
    'NO': 'NO',
    'OM': 'OM',
    'PK': 'PK',
    'PW': 'PW',
    'PS': 'PS',
    'PA': 'PA',
    'PG': 'PG',
    'PY': 'PY',
    'PE': 'PE',
    'PH': 'PH',
    'PN': 'PN',
    'PL': 'PL',
    'PT': 'PT',
    'PR': 'PR',
    'QA': 'QA',
    'RE': 'RE',
    'RO': 'RO',
    'RU': 'RU',
    'RW': 'RW',
    'BL': 'BL',
    'SH': 'SH',
    'KN': 'KN',
    'LC': 'LC',
    'MF': 'MF',
    'PM': 'PM',
    'VC': 'VC',
    'WS': 'WS',
    'SM': 'SM',
    'ST': 'ST',
    'SA': 'SA',
    'SN': 'SN',
    'RS': 'RS',
    'SC': 'SC',
    'SL': 'SL',
    'SG': 'SG',
    'SX': 'SX',
    'SK': 'SK',
    'SI': 'SI',
    'SB': 'SB',
    'SO': 'SO',
    'ZA': 'ZA',
    'GS': 'GS',
    'SS': 'SS',
    'ES': 'ES',
    'LK': 'LK',
    'SD': 'SD',
    'SR': 'SR',
    'SJ': 'SJ',
    'SE': 'SE',
    'CH': 'CH',
    'SY': 'SY',
    'TW': 'TW',
    'TJ': 'TJ',
    'TZ': 'TZ',
    'TH': 'TH',
    'TL': 'TL',
    'TG': 'TG',
    'TK': 'TK',
    'TO': 'TO',
    'TT': 'TT',
    'TN': 'TN',
    'TR': 'TR',
    'TM': 'TM',
    'TC': 'TC',
    'TV': 'TV',
    'UG': 'UG',
    'UA': 'UA',
    'AE': 'AE',
    'GB': 'GB',
    'US': 'US',
    'UM': 'UM',
    'UY': 'UY',
    'UZ': 'UZ',
    'VU': 'VU',
    'VE': 'VE',
    'VN': 'VN',
    'VG': 'VG',
    'VI': 'VI',
    'WF': 'WF',
    'EH': 'EH',
    'YE': 'YE',
    'ZM': 'ZM',
    'ZW': 'ZW',
    'AFGHANISTAN': 'AF',
    'LAND ISLANDS': 'AX',
    'ALBANIA': 'AL',
    'ALGERIA': 'DZ',
    'AMERICAN SAMOA': 'AS',
    'ANDORRA': 'AD',
    'ANGOLA': 'AO',
    'ANGUILLA': 'AI',
    'ANTARCTICA': 'AQ',
    'ANTIGUA AND BARBUDA': 'AG',
    'ARGENTINA': 'AR',
    'ARMENIA': 'AM',
    'ARUBA': 'AW',
    'AUSTRALIA': 'AU',
    'AUSTRIA': 'AT',
    'AZERBAIJAN': 'AZ',
    'BAHAMAS': 'BS',
    'BAHRAIN': 'BH',
    'BARBADOS': 'BB',
    'BELARUS': 'BY',
    'BELGIUM': 'BE',
    'BELIZE': 'BZ',
    'BENIN': 'BJ',
    'BERMUDA': 'BM',
    'BOLIVIA PLURINATIONAL STATE OF': 'BO',
    'BOSNIA AND HERZEGOVINA': 'BA',
    'BOTSWANA': 'BW',
    'BRAZIL': 'BR',
    'BULGARIA': 'BG',
    'CABO VERDE': 'CV',
    'CAMBODIA': 'KH',
    'CAMEROON': 'CM',
    'CANADA': 'CA',
    'CAYMAN ISLANDS': 'KY',
    'CHAD': 'TD',
    'CHILE': 'CL',
    'CHINA': 'CN',
    'COLOMBIA': 'CO',
    'COMOROS': 'KM',
    'CONGO DEMOCRATIC REPUBLIC OF THE': 'CD',
    'COOK ISLANDS': 'CK',
    'COSTA RICA': 'CR',
    'CROATIA': 'HR',
    'CUBA': 'CU',
    'CYPRUS': 'CY',
    'CZECHIA': 'CZ',
    'DJIBOUTI': 'DJ',
    'DOMINICA': 'DM',
    'ECUADOR': 'EC',
    'EGYPT': 'EG',
    'EL SALVADOR': 'SV',
    'EQUATORIAL GUINEA': 'GQ',
    'ERITREA': 'ER',
    'ESTONIA': 'EE',
    'ETHIOPIA': 'ET',
    'FALKLAND ISLANDS MALVINAS': 'FK',
    'FIJI': 'FJ',
    'FINLAND': 'FI',
    'FRENCH GUIANA': 'GF',
    'FRENCH POLYNESIA': 'PF',
    'GAMBIA': 'GM',
    'GEORGIA': 'GE',
    'GHANA': 'GH',
    'GUATEMALA': 'GT',
    'GUINEABISSAU': 'GW',
    'GUYANA': 'GY',
    'HAITI': 'HT',
    'HONDURAS': 'HN',
    'INDIA': 'IN',
    'INDONESIA': 'ID',
    'IRAN ISLAMIC REPUBLIC OF': 'IR',
    'IRAQ': 'IQ',
    'ISRAEL': 'IL',
    'JAMAICA': 'JM',
    'JORDAN': 'JO',
    'KAZAKHSTAN': 'KZ',
    'KENYA': 'KE',
    'KUWAIT': 'KW',
    'KYRGYZSTAN': 'KG',
    'LATVIA': 'LV',
    'LIBERIA': 'LR',
    'LITHUANIA': 'LT',
    'MALAWI': 'MW',
    'MALDIVES': 'MV',
    'MALI': 'ML',
    'MARTINIQUE': 'MQ',
    'MAURITANIA': 'MR',
    'MICRONESIA FEDERATED STATES OF': 'FM',
    'MOLDOVA REPUBLIC OF': 'MD',
    'MONGOLIA': 'MN',
    'MOROCCO': 'MA',
    'MOZAMBIQUE': 'MZ',
    'MYANMAR': 'MM',
    'NAMIBIA': 'NA',
    'NAURU': 'NR',
    'NEW CALEDONIA': 'NC',
    'NICARAGUA': 'NI',
    'NIUE': 'NU',
    'NORTH MACEDONIA': 'MK',
    'NORTHERN MARIANA ISLANDS': 'MP',
    'NORWAY': 'NO',
    'OMAN': 'OM',
    'PALAU': 'PW',
    'PALESTINE STATE OF': 'PS',
    'PANAMA': 'PA',
    'PAPUA NEW GUINEA': 'PG',
    'PARAGUAY': 'PY',
    'PERU': 'PE',
    'PHILIPPINES': 'PH',
    'PITCAIRN': 'PN',
    'POLAND': 'PL',
    'PORTUGAL': 'PT',
    'PUERTO RICO': 'PR',
    'QATAR': 'QA',
    'ROMANIA': 'RO',
    'RWANDA': 'RW',
    'SAINT HELENA ASCENSION AND TRISTAN DA CUNHA': 'SH',
    'SAINT MARTIN FRENCH PART': 'MF',
    'SAMOA': 'WS',
    'SAN MARINO': 'SM',
    'SAO TOME AND PRINCIPE': 'ST',
    'SAUDI ARABIA': 'SA',
    'SENEGAL': 'SN',
    'SERBIA': 'RS',
    'SEYCHELLES': 'SC',
    'SIERRA LEONE': 'SL',
    'SINGAPORE': 'SG',
    'SINT MAARTEN DUTCH PART': 'SX',
    'SLOVAKIA': 'SK',
    'SLOVENIA': 'SI',
    'SOLOMON ISLANDS': 'SB',
    'SOMALIA': 'SO',
    'SOUTH AFRICA': 'ZA',
    'SOUTH SUDAN': 'SS',
    'SRI LANKA': 'LK',
    'SUDAN': 'SD',
    'SURINAME': 'SR',
    'SVALBARD AND JAN MAYEN': 'SJ',
    'TAIWAN PROVINCE OF CHINA': 'TW',
    'TAJIKISTAN': 'TJ',
    'TANZANIA UNITED REPUBLIC OF': 'TZ',
    'TIMORLESTE': 'TL',
    'TOGO': 'TG',
    'TOKELAU': 'TK',
    'TONGA': 'TO',
    'TRINIDAD AND TOBAGO': 'TT',
    'TUNISIA': 'TN',
    'TURKEY': 'TR',
    'TURKS AND CAICOS ISLANDS': 'TC',
    'TUVALU': 'TV',
    'UGANDA': 'UG',
    'URUGUAY': 'UY',
    'UZBEKISTAN': 'UZ',
    'VANUATU': 'VU',
    'VENEZUELA BOLIVARIAN REPUBLIC OF': 'VE',
    'YEMEN': 'YE',
    'ZAMBIA': 'ZM',
    'ZIMBABWE': 'ZW'
}